# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:
    #stock: value

services:
    app.check_stock:
        class: AppBundle\Service\CheckStock
        arguments: []