# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    bucket: 'cart'
    tarnsaction_id: 'change this value when use app for validate card'

services:
    app.check_stock:
        class: AppBundle\Service\CheckStock
        arguments: []
    app.session_storage:
        class: AppBundle\Service\SessionStorage
        arguments: ['%bucket%']
    app.basket:
        class: AppBundle\Service\Basket
        arguments: ['@app.session_storage', '@doctrine.orm.entity_manager', '@app.check_stock']
    app.event:
        class: AppBundle\Service\Events\Event
        arguments: []
    app.order_was_created:
        class: AppBundle\Service\Events\OrderWasCreated
        arguments: ['@doctrine', '@app.basket', '@doctrine.orm.entity_manager']
    app.empty_basket:
        class: AppBundle\Service\Handlers\EmptyBasket
        arguments: []
    app.mark_order_paid:
        class: AppBundle\Service\Handlers\MarkOrderPaid
        arguments: []
    app.record_fail_paymend:
        class: AppBundle\Service\Handlers\RecordFailPayment
        arguments: []
    app.record_pass_paymend:
        class: AppBundle\Service\Handlers\RecordPassPayment
        arguments: []
    app.update_stock:
        class: AppBundle\Service\Handlers\UpdateStock
        arguments: []
    app.update_virtual_cash:
        class: AppBundle\Service\Handlers\UpdateVirtualCash
        arguments: []
    app.update_virtual_cash_owners:
        class: AppBundle\Service\Handlers\UpdateVirtualCashOwners
        arguments: []
    app.get_data_from_db:
        class: AppBundle\Service\GetDataFromDB
        arguments: ['@doctrine.orm.entity_manager']
    app.pagination:
        class: AppBundle\Service\Pagination
        arguments: ['@doctrine.orm.entity_manager']
    app.promotion_service:
        class: AppBundle\Service\PromotionsService
        arguments: ['@doctrine', '@doctrine.orm.entity_manager']