# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    bucket: 'cart'

services:
    app.check_stock:
        class: AppBundle\Service\CheckStock
        arguments: []
    app.session_storage:
        class: AppBundle\Service\SessionStorage
        arguments: ['%bucket%']
    app.basket:
        class: AppBundle\Service\Basket
        arguments: ['@app.session_storage', '@doctrine.orm.entity_manager', '@app.check_stock']